name: Release SDK

on:
  workflow_dispatch:
    inputs:
      SDK_NAME:
        description: 'SDK NAme: A name of the sdk to release (e.g. BlinkReceipt or BlinkEReceipt)'
        required: true
        default: 'BlinkReceipt'
      SDK_VERSION:
        description: 'SDK Version: A version of the SDK to release'
        required: true
        default: ''
      AWS_KEY_ID:
        description: 'A key ID for the AWS CLI'
        required: true
        default: ''
      AWS_KEY:
        description: 'A key for the AWS CLI'
        required: true
        default: ''

jobs:
  Release SDK:
    runs-on: [macos-latest]
    env:
      SDK_NAME: ${{ github.event.inputs.SDK_NAME }}
      SDK_VERSION: ${{ github.event.inputs.SDK_VERSION }}
      AWS_KEY_ID: ${{ github.event.inputs.AWS_KEY_ID }}
      AWS_KEY: ${{ github.event.inputs.AWS_KEY }}

    steps:
    - name: Install AWS CLI
      run: |
        curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
        chmod +x install-aws.sh
        ./install-aws.sh "v2" "amd64"
        rm install-aws.sh
        export AWS_ACCESS_KEY_ID=$AWS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$AWS_KEY
        export AWS_DEFAULT_REGION='us-east-1'

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download artifacts from AWS S3
      run: aws s3 cp s3://ios-app-bucket-commerce/${SDK_VERSION}_${SDK_NAME}_sdk/sdk . --recursive

    - name: Add files to the git tree
      run: |
        git switch -c release/${SDK_VERSION}
        git add .
        git commit -m "Release ${SDK_VERSION}"
        gh pr create --base master --head release/${SDK_VERSION} --title "Release ${SDK_NAME} ${SDK_VERSION}" --body ""

